variables:
  - name: 'ver.Patch'
    value: $[counter(variables['ver.Minor'], 1)]

name: DEV-ver$(ver.Major).$(ver.Minor).$(ver.Patch)

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: e2e
  pool:
    vmImage: ubuntu-latest
  container: mcr.microsoft.com/playwright:v1.32.0-focal
  steps:
  - checkout: self

  - task: Cache@2
    inputs:
      key: '"node" | "$(Agent.OS)" | package.lock'
      restoreKeys: |
        npm | "$(Agent.OS)"
        npm
      path: "$(Pipeline.Workspace)/test/e2e/.yarn"
    displayName: Cache node packages

  - task: Bash@3
    displayName: 'Run Playwright tests'
    inputs:
      workingDirectory: 'test/e2e'
      targetType: 'inline'
      failOnStderr: true
      script: |
        npm ci
        npx playwright test
    env:
      CI: true

- job: deploy
  dependsOn: e2e
  pool:
    vmImage: ubuntu-latest
  steps:

    - checkout: self

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Firebase.json'
      inputs:
        PathtoPublish: firebase.json
        ArtifactName: drop/

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/'
        ArtifactName: 'drop'
        publishLocation: 'Container'
