trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: e2e
  pool:
    vmImage: ubuntu-latest
  container: mcr.microsoft.com/playwright:v1.32.0-focal
  steps:
  - checkout: self

  - task: Cache@2
    inputs:
      key: '"npm ci" | "$(Agent.OS)" | test/e2e/package-lock.json'
      restoreKeys: |
        npm ci | "$(Agent.OS)"
        npm ci
      path: "$(Pipeline.Workspace)/test/e2e/node_modules"
    displayName: Cache node packages

  - task: Bash@3
    displayName: 'Run Playwright tests'
    inputs:
      workingDirectory: 'test/e2e'
      targetType: 'inline'
      failOnStderr: true
      script: |
        npm ci
        npx playwright test
    env:
      CI: true

- job: deploy
  dependsOn: e2e
  pool:
    vmImage: ubuntu-latest
  steps:

    - checkout: self

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Firebase.json'
      inputs:
        PathtoPublish: firebase.json
        ArtifactName: drop/

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/'
        ArtifactName: 'drop'
        publishLocation: 'Container'
