trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: e2e
  pool:
    vmImage: ubuntu-latest
  container: mcr.microsoft.com/playwright:v1.32.0-focal
  steps:
  - checkout: self
  - task: Bash@3
    displayName: 'Run Playwright tests'
    inputs:
      workingDirectory: 'test/e2e'
      targetType: 'inline'
      failOnStderr: true
      env:
        CI: true
      script: |
        npm ci
        npx playwright test

- job: deploy
  dependsOn: e2e
  pool:
    vmImage: ubuntu-latest
  steps:
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Firebase.json'
      inputs:
        PathtoPublish: firebase.json
        ArtifactName: drop/

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build'
      inputs:
        PathtoPublish: public
        ArtifactName: drop/public


