variables:
- group: firebase

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: e2e
  pool:
    vmImage: ubuntu-latest
  container: mcr.microsoft.com/playwright:latest
  steps:

  - checkout: self

  - task: Bash@3
    displayName: 'Run Playwright tests'
    inputs:
      workingDirectory: 'test/e2e'
      targetType: 'inline'
      failOnStderr: true
      script: |
        node --version
        npm --version
        npm ci
        npx playwright test
    env:
      CI: true

- job: deploy
  dependsOn: e2e
  pool:
    vmImage: ubuntu-latest
  steps:

    - checkout: self

    - task: CopyFiles@2
      inputs:
        Contents: |
          public/**
          firebase.json
          .firebaserc
          pipelines/*.sh
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1

    - task: Bash@3
      displayName: Firebase deploy
      inputs:
        targetType: 'inline'
        script: |
          npm install -g firebase-tools
          firebase \
            --debug \
            --config firebase.json \
            --token "$(token)" \
            --project "$(project)" \
            --force \
            -m "$(Build.BuildNumber)" \
            --non-interactive \
            deploy

