variables:
- group: firebase

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: e2e
  pool:
    vmImage: ubuntu-latest
  #container: mcr.microsoft.com/playwright:latest
  steps:

  - checkout: self

  - task: Bash@3
    displayName: 'Install firebase'
    inputs:
      targettype: 'inline'
      script: npm install -g firebase-tools
    env:
      CI: true

  - task: Bash@3
    displayName: 'npm install Firebase functions'
    inputs:
      workingDirectory: 'functions'
      targetType: 'inline'
      script: npm ci
    env:
      CI: true

  - task: Bash@3
    displayName: 'npm install Playwright tests'
    inputs:
      workingDirectory: 'test/e2e'
      targetType: 'inline'
      script: npm ci
    env:
      CI: true

  - task: Bash@3
    displayName: 'Run Playwright tests'
    inputs:
      workingDirectory: 'test/e2e'
      targetType: 'inline'
      failOnStderr: true
      script: |
        firebase use pocketangler-v1-5 --token "$(token)"
        firebase emulators:exec "npx playwright test" --token "$(token)"
    env:
      CI: true

- job: deploy
  dependsOn: e2e
  pool:
    vmImage: ubuntu-latest
  steps:

    - checkout: self

    - task: CopyFiles@2
      inputs:
        Contents: |
          public/**
          firebase.json
          .firebaserc
          pipelines/*.sh
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1

    - task: Bash@3
      displayName: Firebase deploy
      inputs:
        targetType: 'inline'
        script: |
          npm install -g firebase-tools
          (cd functions && npm ci)
          firebase \
            --debug \
            --config firebase.json \
            --token "$(token)" \
            --project "$(project)" \
            --force \
            -m "$(Build.BuildNumber)" \
            --non-interactive \
            deploy

