trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: e2e
  pool:
    vmImage: ubuntu-latest
  container: mcr.microsoft.com/playwright:latest
  steps:

  - checkout: self

  - task: Bash@3
    displayName: 'Run Playwright tests'
    inputs:
      workingDirectory: 'test/e2e'
      targetType: 'inline'
      failOnStderr: true
      script: |
        node --version
        npm --version
        npm ci
        npx playwright test
    env:
      CI: true

- job: deploy
  dependsOn: e2e
  pool:
    vmImage: ubuntu-latest
  steps:

    - checkout: self

    - task: CopyFiles@2
      inputs:
        Contents: |
          public/**
          firebase.json
          .firebaserc
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
