name: Deploy

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: 'functions'

    - run: npm ci
      working-directory: test/e2e

    - run: npx playwright install --with-deps
      working-directory: test/e2e

    - run: |
        DEBUG=pw:browser* npx playwright test
      working-directory: test/e2e
